import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ["latin","thai"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Basic Routing",
  description: "Generated by create next app",
  keywords: ["nextjs", "routing", "react", "typescript", "tailwindcss"],
  authors: [{ name: "Tanawan Songdechagriwut", url: "https://www.sau.ac.th" }],
  creator: "Tanawan Songdechagriwut",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${kanit.className}`}
    >
      <body className="min-h-full flex flex-col">
        <h1 className="text-center text-white-800 font bold">Welcome to SAU</h1>
        <hr />
        {children}
      </body>
    </html>
  );
}
